### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dnshavalli**
This file modified to add readable documentation

### CODE REVIEW

**Review by dnshavalli — COMMENTED** [review]
done

**Review by dnshavalli — COMMENTED** [review]
Reviewed by ramesh

**Comment by dnshavalli** [comment]
Please submit changes before modifying

**Comment by Noorshavalli** [comment]
modify line 4

**Comment by dnshavalli** [comment]
line 4 modified successfully

**Comment by Noorshavalli** [comment]
Verified, working fine

**Comment by Noorshavalli** [comment]
Merged to master branch

**Pull request merged**
